--liquibase formatted sql
--changeset svalenti:2.5.6.0_20210928_03 failOnError:false

CREATE TABLE MOVIMENTI_CONTABILI_INTERNI
(
    ID_MOVIMENTO_CONTABILE  NUMBER(19)            NOT NULL,
    ID_PROPOSTA_DELIBERA    NUMBER(19),
    ID_DETERMINA            NUMBER(19),
    CAPITOLO                VARCHAR2(255 BYTE),
    DESCRIZIONE_CAPITOLO    VARCHAR2(2000 BYTE),
    IMPORTO                 NUMBER(19,2),
    ESERCIZIO               VARCHAR2(255 BYTE),
    ARTICOLO                VARCHAR2(255 BYTE),
    EPF                     VARCHAR2(255 BYTE),
    PDCF                    VARCHAR2(255 BYTE),
    EOS                     VARCHAR2(255 BYTE),
    PROGRESSIVO_SOGGETTO    VARCHAR2(255 BYTE),
    DESCRIZIONE_SOGGETTO    VARCHAR2(2000 BYTE),
    NOTE                    VARCHAR2(4000 BYTE),
    ENTE                    VARCHAR2(255 BYTE)    NOT NULL,
    DATA_INS                DATE                  NOT NULL,
    DATA_UPD                DATE                  NOT NULL,
    UTENTE_INS              VARCHAR2(255 BYTE)    NOT NULL,
    UTENTE_UPD              VARCHAR2(255 BYTE)    NOT NULL,
    VERSION                 NUMBER(19)            DEFAULT 0                     NOT NULL,
    CODICE_MISSIONE         VARCHAR2(255 BYTE),
    CODICE_PROGRAMMA        VARCHAR2(255 BYTE),
    COGNOME                 VARCHAR2(255 BYTE),
    NOME                    VARCHAR2(255 BYTE),
    CF                      VARCHAR2(255 BYTE),
    PIVA                    VARCHAR2(255 BYTE),
    CF_ESTERO               VARCHAR2(255 BYTE),
    PIVA_ESTERO             VARCHAR2(255 BYTE),
    INDIRIZZO               VARCHAR2(255 BYTE),
    LOCALITA                VARCHAR2(255 BYTE),
    COMUNE                  VARCHAR2(255 BYTE),
    PROVINCIA               VARCHAR2(255 BYTE),
    CAP                     VARCHAR2(255 BYTE),
    STATO                   VARCHAR2(255 BYTE),
    TELEFONO                VARCHAR2(255 BYTE),
    EMAIL                   VARCHAR2(255 BYTE),
    PEC                     VARCHAR2(255 BYTE)
)
/

CREATE INDEX ID_MOVCONT_INT_IDX_TIPO_DOC_IK ON MOVIMENTI_CONTABILI_INTERNI
(ID_PROPOSTA_DELIBERA, ID_DETERMINA)
/

CREATE UNIQUE INDEX ID_MOVIMENTO_CONTABILE_INT_IDX ON MOVIMENTI_CONTABILI_INTERNI
(ID_MOVIMENTO_CONTABILE)
/

ALTER TABLE MOVIMENTI_CONTABILI_INTERNI ADD (
  CONSTRAINT ID_MOVIMENTO_CONTABILE_INT_IDX
  PRIMARY KEY
  (ID_MOVIMENTO_CONTABILE)
  USING INDEX ID_MOVIMENTO_CONTABILE_INT_IDX
  ENABLE VALIDATE)
/