--liquibase formatted sql
--changeset rdestasio:2.4.1.0_20200221_01

-------------------
-- Versione 2.4.1.x
-------------------

-- import PARZIALE di GestioneDocumenti
CREATE TABLE GDO_DOCUMENTI ( ID_DOCUMENTO NUMBER, STATO VARCHAR2(255 BYTE), STATO_FIRMA VARCHAR2(255 BYTE), STATO_CONSERVAZIONE VARCHAR2(255 BYTE), ID_ENGINE_ITER NUMBER, ID_DOCUMENTO_ESTERNO NUMBER, TIPO_OGGETTO VARCHAR2(255 BYTE), VALIDO CHAR(1 BYTE) DEFAULT 'Y', UTENTE_INS VARCHAR2(255 BYTE), DATA_INS DATE, UTENTE_UPD VARCHAR2(255 BYTE), DATA_UPD DATE, VERSION NUMBER, RISERVATO CHAR(1 BYTE), ENTE VARCHAR2(255 BYTE) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE TABLE GDO_DOCUMENTI_COLLEGATI ( ID_DOCUMENTO_COLLEGATO NUMBER(19), VERSION NUMBER(19), ID_COLLEGATO NUMBER(19), DATA_INS DATE, ID_DOCUMENTO NUMBER(19), DATA_UPD DATE, ID_TIPO_COLLEGAMENTO NUMBER(19), UTENTE_INS VARCHAR2(255 BYTE), UTENTE_UPD VARCHAR2(255 BYTE), VALIDO CHAR(1 BYTE) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE TABLE GDO_DOCUMENTI_SOGGETTI ( ID_DOCUMENTO_SOGGETTO NUMBER(19), VERSION NUMBER(19), ATTIVO CHAR(1 BYTE), ID_DOCUMENTO NUMBER(19), SEQUENZA NUMBER(10), TIPO_SOGGETTO VARCHAR2(255 BYTE), UNITA_PROGR NUMBER(19), UNITA_DAL DATE, UNITA_OTTICA VARCHAR2(255 BYTE), UTENTE VARCHAR2(255 BYTE) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE TABLE GDO_TIPI_COLLEGAMENTO ( ID_TIPO_COLLEGAMENTO NUMBER, TIPO_COLLEGAMENTO VARCHAR2(255 BYTE), DESCRIZIONE VARCHAR2(255 BYTE), COMMENTO VARCHAR2(4000 BYTE), UTENTE_INS VARCHAR2(255 BYTE), DATA_INS DATE, UTENTE_UPD VARCHAR2(255 BYTE), DATA_UPD DATE, VALIDO CHAR(1 BYTE) DEFAULT 'Y', ENTE VARCHAR2(255 BYTE) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE TABLE GDO_TIPI_DOCUMENTO ( ID_TIPO_DOCUMENTO NUMBER, DESCRIZIONE VARCHAR2(255 BYTE), COMMENTO VARCHAR2(4000 BYTE), CONSERVAZIONE_SOSTITUTIVA CHAR(1 BYTE), PROGRESSIVO_CFG_ITER NUMBER, TESTO_OBBLIGATORIO CHAR(1 BYTE), VALIDO CHAR(1 BYTE), UTENTE_INS VARCHAR2(255 BYTE), DATA_INS DATE, UTENTE_UPD VARCHAR2(255 BYTE), DATA_UPD DATE, VERSION NUMBER, CODICE VARCHAR2(255 BYTE), ACRONIMO VARCHAR2(255 BYTE), ENTE VARCHAR2(255 BYTE), ID_CARATTERISTICA_TIPOLOGIA NUMBER, ID_MODELLO_TESTO NUMBER ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE INDEX GDO_DOCO_DOCU2_FK ON GDO_DOCUMENTI_COLLEGATI (ID_DOCUMENTO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_DOCO_DOCU3_FK ON GDO_DOCUMENTI_COLLEGATI (ID_COLLEGATO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_DOCO_TICO_FK ON GDO_DOCUMENTI_COLLEGATI (ID_TIPO_COLLEGAMENTO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_DOCU_ENIT_FK ON GDO_DOCUMENTI (ID_ENGINE_ITER) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_DOCUMENTI_COLLEGATI_PK ON GDO_DOCUMENTI_COLLEGATI (ID_DOCUMENTO_COLLEGATO) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_DOCUMENTI_PK ON GDO_DOCUMENTI (ID_DOCUMENTO) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_DOCUMENTI_SOGGETTI_PK ON GDO_DOCUMENTI_SOGGETTI (ID_DOCUMENTO_SOGGETTO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_DOCU_TIOG_FK ON GDO_DOCUMENTI (TIPO_OGGETTO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_ID_DOCU_ESTERNO_IK ON GDO_DOCUMENTI (ID_DOCUMENTO_ESTERNO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_TICO_IDX ON GDO_TIPI_COLLEGAMENTO (TIPO_COLLEGAMENTO) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_TIPI_COLLEGAMENTO_PK ON GDO_TIPI_COLLEGAMENTO (ID_TIPO_COLLEGAMENTO) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_TIPI_DOCUMENTO_PK ON GDO_TIPI_DOCUMENTO (ID_TIPO_DOCUMENTO) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_TIPO_ACRONIMO_UK ON GDO_TIPI_DOCUMENTO (ACRONIMO) LOGGING NOPARALLEL
/
CREATE INDEX PROTSOG_TIPSOG_FK ON GDO_DOCUMENTI_SOGGETTI (TIPO_SOGGETTO) LOGGING NOPARALLEL
/
CREATE INDEX UNITA_IDX ON GDO_DOCUMENTI_SOGGETTI (UNITA_PROGR, UNITA_DAL, UNITA_OTTICA) LOGGING NOPARALLEL
/
ALTER TABLE GDO_DOCUMENTI ADD (  CONSTRAINT GDO_DOCUMENTI_PK PRIMARY KEY (ID_DOCUMENTO) USING INDEX GDO_DOCUMENTI_PK ENABLE VALIDATE)
/

-- modifica dei file allegati per extend file_documento
ALTER TABLE FILE_ALLEGATI ADD (TIPO VARCHAR2(255 BYTE) DEFAULT 'FILE_ALLEGATO')
/
ALTER TABLE FILE_ALLEGATI ADD (CODICE VARCHAR2(255 BYTE) NULL)
/
ALTER TABLE FILE_ALLEGATI ADD (ID_MODELLO_TESTO NUMBER NULL)
/
ALTER TABLE FILE_ALLEGATI ADD CONSTRAINT FAMOD_GTEMOD_FK FOREIGN KEY (ID_MODELLO_TESTO) REFERENCES GTE_MODELLI (ID_MODELLO) ENABLE VALIDATE
/
ALTER TABLE FILE_ALLEGATI ADD (ID_DOCUMENTO NUMBER)
/
ALTER TABLE FILE_ALLEGATI ADD CONSTRAINT FADOC_GDODOC_FK FOREIGN KEY (ID_DOCUMENTO) REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO) ENABLE VALIDATE
/
ALTER TABLE FILE_ALLEGATI ADD (REVISIONE_STORICO NUMBER NULL)
/
ALTER TABLE FILE_ALLEGATI ADD (SEQUENZA NUMBER NULL)
/

-- sedute stampe
DROP TABLE ODG_SEDUTE_STAMPE
/
CREATE TABLE ODG_SEDUTE_STAMPE ( ID_SEDUTA_STAMPA NUMBER(19), VERSION NUMBER(19), ID_COMMISSIONE_STAMPA NUMBER(19), ID_SEDUTA NUMBER(19), VALIDO NUMBER(1), DATA_INS DATE, DATA_UPD DATE, UTENTE_INS VARCHAR(255), UTENTE_UPD VARCHAR(255), ENTE VARCHAR(255), RISERVATO NUMBER(1), TIPO_OGGETTO VARCHAR(255), ID_ENGINE_ITER NUMBER, STATO VARCHAR(255), STATO_FIRMA VARCHAR(255), STATO_CONSERVAZIONE VARCHAR(255), ID_DOCUMENTO_ESTERNO NUMBER) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE INDEX ODGSEDSTA_ODGCOMSTA_FK ON ODG_SEDUTE_STAMPE (ID_COMMISSIONE_STAMPA) LOGGING NOPARALLEL
/
CREATE INDEX ODGSEDSTA_ODGSED_FK ON ODG_SEDUTE_STAMPE (ID_SEDUTA) LOGGING NOPARALLEL
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (  PRIMARY KEY (ID_SEDUTA_STAMPA) ENABLE VALIDATE)
/

-- aggiungo i campi utente/data/ins/upd ai file allegati
ALTER TABLE FILE_ALLEGATI ADD (data_ins DATE)
/
ALTER TABLE FILE_ALLEGATI ADD (data_upd DATE)
/
ALTER TABLE FILE_ALLEGATI ADD (utente_ins varchar2(255))
/
ALTER TABLE FILE_ALLEGATI ADD (utente_upd varchar2(255))
/
ALTER TABLE FILE_ALLEGATI ADD (valido char(1) default 'Y')
/
update file_allegati set data_ins = sysdate, data_upd = sysdate, utente_ins = (select utente from ad4_v_utenti where nominativo = 'AGSDE2'), utente_upd = (select utente from ad4_v_utenti where nominativo = 'AGSDE2')
/
ALTER TABLE FILE_ALLEGATI MODIFY(DATA_INS  NOT NULL)
/
ALTER TABLE FILE_ALLEGATI MODIFY(DATA_UPD  NOT NULL)
/
ALTER TABLE FILE_ALLEGATI MODIFY(UTENTE_INS  NOT NULL)
/
ALTER TABLE FILE_ALLEGATI MODIFY(UTENTE_UPD  NOT NULL)
/
ALTER TABLE FILE_ALLEGATI MODIFY(VALIDO  NOT NULL)
/

-- modifica di odg_commissione_stampa per farla diventare come una "tipologia" di documento
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (USO_NEL_VISUALIZZATORE CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/
update odg_commissioni_stampe set uso_nel_visualizzatore = 'Y' where codice in ('CONVOCAZIONE', 'VERBALE')
/
UPDATE odg_commissioni_stampe s SET s.codice = (SELECT CASE WHEN m.tipo_modello = 'ODG_CONVOCAZIONE_SEDUTA' THEN 'CONVOCAZIONE' WHEN m.tipo_modello = 'ODG_VERBALE_SEDUTA' THEN 'VERBALE' ELSE 'DELIBERA' END CASE FROM gte_modelli m WHERE m.id_modello = s.id_modello) WHERE s.codice IN ('STAMPA')
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (TITOLO VARCHAR(255 BYTE))
/
update odg_commissioni_stampe s set s.titolo = (select M.NOME from gte_modelli m where M.ID_MODELLO = S.ID_MODELLO)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE MODIFY (TITOLO NOT NULL)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (DESCRIZIONE VARCHAR(255 BYTE))
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (PROGRESSIVO_CFG_ITER NUMBER)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (ID_CARATTERISTICA_TIPOLOGIA NUMBER)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD CONSTRAINT ODGCOMST_CARTIP_FK FOREIGN KEY (ID_CARATTERISTICA_TIPOLOGIA) REFERENCES CARATTERISTICHE_TIPOLOGIE (ID_CARATTERISTICA_TIPOLOGIA) ENABLE VALIDATE
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (data_ins DATE)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (data_upd DATE)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (utente_ins varchar2(255))
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (utente_upd varchar2(255))
/
ALTER TABLE ODG_COMMISSIONI_STAMPE ADD (valido char(1) default 'Y')
/
update ODG_COMMISSIONI_STAMPE set data_ins = sysdate, data_upd = sysdate, utente_ins = (select utente from ad4_v_utenti where nominativo = 'AGSDE2'), utente_upd = (select utente from ad4_v_utenti where nominativo = 'AGSDE2')
/
ALTER TABLE ODG_COMMISSIONI_STAMPE MODIFY(DATA_INS  NOT NULL)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE MODIFY(DATA_UPD  NOT NULL)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE MODIFY(UTENTE_INS  NOT NULL)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE MODIFY(UTENTE_UPD  NOT NULL)
/
ALTER TABLE ODG_COMMISSIONI_STAMPE MODIFY(VALIDO  NOT NULL)
/

-- aggiungo il tipo di oggetto documento_odg ai tipi disponibili nel configuratore
Insert into WKF_DIZ_TIPI_OGGETTO (CODICE, DESCRIZIONE, ITERABILE, NOME, OGGETTI_FIGLI, VALIDO) Values ('SEDUTA_STAMPA', 'Documento di seduta (Verbale o Convocazione)', 'Y', 'Stampa di Seduta', NULL, 'Y')
/
update notifiche set oggetti = oggetti||'#SEDUTA_STAMPA' where tipo_notifica = 'ASSEGNAZIONE'
/

-- aggiungo la tabella di competenze
CREATE TABLE GDO_DOCUMENTI_COMPETENZE ( ID_DOCUMENTO_COMPETENZA NUMBER(19), VERSION NUMBER(19), CANCELLAZIONE CHAR(1 BYTE), ID_CFG_COMPETENZA NUMBER(19), LETTURA CHAR(1 BYTE), MODIFICA CHAR(1 BYTE), ID_DOCUMENTO NUMBER(19), RUOLO VARCHAR2(255 BYTE), UNITA_PROGR NUMBER(19), UNITA_DAL DATE, UNITA_OTTICA VARCHAR2(255 BYTE), UTENTE VARCHAR2(255 BYTE) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE INDEX GDO_DOCO_DOCU_FK ON GDO_DOCUMENTI_COMPETENZE (ID_DOCUMENTO) LOGGING NOPARALLEL
/
CREATE INDEX GDO_DOCO_WKFCFGCOM_FK ON GDO_DOCUMENTI_COMPETENZE (ID_CFG_COMPETENZA) LOGGING NOPARALLEL
/
CREATE UNIQUE INDEX GDO_DOCUMENTI_COMPETENZE_PK ON GDO_DOCUMENTI_COMPETENZE (ID_DOCUMENTO_COMPETENZA) LOGGING NOPARALLEL
/
ALTER TABLE GDO_DOCUMENTI_COMPETENZE ADD (  CONSTRAINT GDO_DOCUMENTI_COMPETENZE_PK PRIMARY KEY (ID_DOCUMENTO_COMPETENZA) USING INDEX GDO_DOCUMENTI_COMPETENZE_PK ENABLE VALIDATE)
/
ALTER TABLE GDO_DOCUMENTI_COMPETENZE ADD (  CONSTRAINT GDO_DOCO_DOCU_FK FOREIGN KEY (ID_DOCUMENTO) REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO) ON DELETE CASCADE ENABLE VALIDATE,  CONSTRAINT GDO_DOCO_WKFCFGCOM_FK FOREIGN KEY (ID_CFG_COMPETENZA) REFERENCES WKF_CFG_COMPETENZE (ID_CFG_COMPETENZA) ENABLE VALIDATE)
/

-- aggiungo i dati di protocollo sulla seduta stampa
-- classifica e fascicoli in Delibera
ALTER TABLE ODG_SEDUTE_STAMPE ADD (CLASSIFICA_CODICE  VARCHAR2(255 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (CLASSIFICA_DESCRIZIONE  VARCHAR2(255 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (CLASSIFICA_DAL  DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (FASCICOLO_NUMERO  VARCHAR2(255 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (FASCICOLO_ANNO  NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (FASCICOLO_OGGETTO  VARCHAR2(4000 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (NUMERO_PROTOCOLLO  NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DATA_NUMERO_PROTOCOLLO  DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (ANNO_PROTOCOLLO  NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (REGISTRO_PROTOCOLLO  VARCHAR2(255 BYTE))
/

-- aggiungo id_documento ai firmatari:
ALTER TABLE FIRMATARI ADD (ID_DOCUMENTO NUMBER(19))
/
ALTER TABLE FIRMATARI ADD CONSTRAINT FIRM_DOC_FK FOREIGN KEY(ID_DOCUMENTO) REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO) ENABLE VALIDATE
/

-- allineo l'azione di apertura della popup di firma spostata in firmaAction
begin
    for c in (select a.*
      from wkf_diz_azioni a
         , wkf_diz_pulsanti_azioni pa
     where a.nome_metodo = 'apriPopupFirma'
       and a.nome_bean = 'firmaAction'
       and a.id_azione = pa.id_azione) loop

       update wkf_diz_pulsanti_azioni a
          set a.id_azione = (select id_azione
                               from wkf_diz_azioni
                               where nome_metodo  = c.nome_metodo
                                 and nome_bean    = 'clientAction'
                                 and tipo         = c.tipo
                                 and tipo_oggetto = c.tipo_oggetto)
        where a.id_azione = c.id_azione;

    end loop;
end;
/

delete from wkf_diz_azioni where nome_metodo = 'apriPopupFirma' and nome_bean = 'firmaAction'
/

update wkf_diz_azioni set nome_bean = 'firmaAction' where nome_bean = 'clientAction' and nome_metodo = 'apriPopupFirma'
/

-- aggiungo la tabella per lo storico delle sedute stampe
CREATE TABLE ODG_SEDUTE_STAMPE_STORICO
(
   ID_SEDUTA_STAMPA_STORICO        NUMBER (19),
   VERSION                         NUMBER (19),
   CLASSIFICA_CODICE               VARCHAR2 (255 BYTE),
   CLASSIFICA_DAL                  DATE,
   CLASSIFICA_DESCRIZIONE          VARCHAR2 (255 BYTE),
   ID_COMMISSIONE_STAMPA           NUMBER (19),
   DATA_NUMERO_PROTOCOLLO          DATE,
   DATA_INS                        DATE,
   ENTE                            VARCHAR2 (255 BYTE),
   FASCICOLO_ANNO                  NUMBER (10),
   FASCICOLO_NUMERO                VARCHAR2 (255 BYTE),
   FASCICOLO_OGGETTO               VARCHAR2 (4000 BYTE),
   ID_SEDUTA_STAMPA                NUMBER (19),
   ID_DOCUMENTO_ESTERNO            NUMBER (19),
   ID_ENGINE_ITER                  NUMBER (19),
   DATA_UPD                        DATE,
   ID_MODELLO_TESTO                NUMBER (19),
   NUMERO_PROTOCOLLO               NUMBER (10),
   ANNO_PROTOCOLLO                 NUMBER (10),
   ID_SEDUTA                       NUMBER (19),
   REGISTRO_PROTOCOLLO             VARCHAR2 (255 BYTE),
   REVISIONE                       NUMBER (19),
   RISERVATO                       CHAR (1 BYTE),
   STATO                           VARCHAR2 (255 BYTE),
   STATO_CONSERVAZIONE             VARCHAR2 (255 BYTE),
   STATO_FIRMA                     VARCHAR2 (255 BYTE),
   ID_ENGINE_STEP                  NUMBER (19),
   ID_FILE_ALLEGATO_TESTO          NUMBER (19),
   UTENTE_INS                      VARCHAR2 (255 BYTE),
   UTENTE_UPD                      VARCHAR2 (255 BYTE),
   VALIDO                          CHAR (1 BYTE),
   VERSIONE_DOCUMENTO_ESTERNO      NUMBER (19),
   XML_SOGGETTI                    CLOB
)
/

ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (  PRIMARY KEY (ID_SEDUTA_STAMPA_STORICO) ENABLE VALIDATE)
/

-- aggiungo i dati di pubblicazione sulle stampe e stampe_storico
ALTER TABLE ODG_SEDUTE_STAMPE ADD (ANNO_ALBO NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DATA_FINE_PUBBLICAZIONE DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DATA_FINE_PUBBLICAZIONE_2 DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DATA_MIN_PUBBLICAZIONE DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DATA_PUBBLICAZIONE DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DATA_PUBBLICAZIONE_2 DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (DA_PUBBLICARE CHAR(1 BYTE) DEFAULT 'N')
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (GIORNI_PUBBLICAZIONE NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (ID_DOCUMENTO_ALBO NUMBER(19))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (NUMERO_ALBO NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (PUBBLICA_REVOCA CHAR(1 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (PUBBLICA_NEL_VISUALIZZATORE CHAR(1 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (NOTE VARCHAR(4000 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (ID_DOCUMENTO_LETTERA NUMBER(19))
/
ALTER TABLE ODG_SEDUTE_STAMPE ADD (RIFERIMENTI_PEC VARCHAR(255 BYTE))
/

ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (ANNO_ALBO NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (DATA_FINE_PUBBLICAZIONE DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (DATA_FINE_PUBBLICAZIONE_2 DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (DATA_MIN_PUBBLICAZIONE DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (DATA_PUBBLICAZIONE DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (DATA_PUBBLICAZIONE_2 DATE)
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (DA_PUBBLICARE CHAR(1 BYTE) DEFAULT 'N')
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (GIORNI_PUBBLICAZIONE NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (ID_DOCUMENTO_ALBO NUMBER(19))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (NUMERO_ALBO NUMBER(10))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (PUBBLICA_REVOCA CHAR(1 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (PUBBLICA_NEL_VISUALIZZATORE CHAR(1 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (NOTE VARCHAR(4000 BYTE))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (ID_DOCUMENTO_LETTERA NUMBER(19))
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO ADD (RIFERIMENTI_PEC VARCHAR(255 BYTE))
/

-- http://svi-redmine/issues/24474 gestione dell'INCARICATO
ALTER TABLE TIPI_DELIBERA ADD (INCARICATO_OBBLIGATORIO CHAR(1 BYTE) DEFAULT 'N')
/

ALTER TABLE TIPI_DETERMINA ADD (INCARICATO_OBBLIGATORIO CHAR(1 BYTE) DEFAULT 'N')
/

-- http://svi-redmine/issues/24611 campi aggiuntivi agli oggetti ricorrenti
ALTER TABLE OGGETTI_RICORRENTI ADD (CIG_OBBLIGATORIO CHAR(1 BYTE) DEFAULT 'N' NOT NULL, SERVIZIO_FORNITURA VARCHAR (255 BYTE), TIPO VARCHAR (255 BYTE), NORMA VARCHAR (4000 BYTE), MODALITA VARCHAR (4000 BYTE))
/

-- il campo MOTIVAZIONE_SCADENZA è stato rinominato in MOTIVAZIONE
update wkf_diz_azioni set nome_metodo = 'proteggiCampo_MOTIVAZIONE' where nome_metodo = 'proteggiCampo_MOTIVAZIONE_SCADENZA'
/

update wkf_diz_azioni set nome_metodo = 'abilitaCampo_MOTIVAZIONE' where nome_metodo = 'abilitaCampo_MOTIVAZIONE_SCADENZA'
/

-- migliore gestione dei webservice di integrazione:

-- codice esterno per identificare la tipologia di allegato:
ALTER TABLE TIPI_ALLEGATO ADD (CODICE_ESTERNO VARCHAR2(255 BYTE) NULL)
/

-- aggiungo i campi id e version per le varie determine/delibere/allegati esterni
ALTER TABLE ag_acquisizione_determine add (ID_DETERMINA_ESTERNA NUMBER, VERSION  NUMBER DEFAULT 0 NOT NULL)
/
update ag_acquisizione_determine set ID_DETERMINA_ESTERNA = hibernate_sequence.nextval
/
ALTER TABLE ag_acquisizione_determine MODIFY(ID_DETERMINA_ESTERNA NOT NULL)
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE add (ID_PROPOSTA_DELIBERA_ESTERNA NUMBER, VERSION  NUMBER DEFAULT 0 NOT NULL)
/
update AG_ACQUISIZIONE_DELIBERE set ID_PROPOSTA_DELIBERA_ESTERNA = hibernate_sequence.nextval
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE MODIFY(ID_PROPOSTA_DELIBERA_ESTERNA NOT NULL)
/
ALTER TABLE ag_acquisizione_allegati add (ID_ALLEGATO_ESTERNO NUMBER NULL, VERSION  NUMBER DEFAULT 0 NOT NULL, ID_DETERMINA_ESTERNA NUMBER, ID_PROPOSTA_DELIBERA_ESTERNA NUMBER)
/
update ag_acquisizione_allegati set ID_ALLEGATO_ESTERNO = hibernate_sequence.nextval
/
ALTER TABLE ag_acquisizione_allegati MODIFY(ID_ALLEGATO_ESTERNO NOT NULL)
/

-- aggiorno gli id sugli allegati
update ag_acquisizione_allegati a set a.id_determina_esterna = (select d.id_determina_esterna from ag_acquisizione_determine d where d.applicativo_esterno = a.applicativo_esterno and d.id_doc_esterno = a.id_doc_esterno)
/
update ag_acquisizione_allegati a set a.id_proposta_delibera_esterna = (select d.id_proposta_delibera_esterna from ag_acquisizione_delibere d where d.applicativo_esterno = a.applicativo_esterno and d.id_doc_esterno = a.id_doc_esterno)
/

-- elimino le chiavi preeesistenti
ALTER TABLE AG_ACQUISIZIONE_ALLEGATI DROP PRIMARY KEY CASCADE
/
ALTER TABLE AG_ACQUISIZIONE_DETERMINE DROP PRIMARY KEY CASCADE
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE DROP PRIMARY KEY CASCADE
/

-- aggiungo il codice della tipologia di allegato
alter table ag_acquisizione_allegati add (ID_DOC_ESTERNO_TMP VARCHAR2(255 BYTE), ID_DOC_ALLEGATO_TMP VARCHAR2(255 BYTE))
/

update ag_acquisizione_allegati set id_doc_esterno_tmp = id_doc_esterno, id_doc_allegato_tmp = id_doc_allegato
/

ALTER TABLE AG_ACQUISIZIONE_ALLEGATI DROP COLUMN ID_DOC_ESTERNO
/

ALTER TABLE AG_ACQUISIZIONE_ALLEGATI RENAME COLUMN ID_DOC_ESTERNO_TMP TO ID_DOC_ESTERNO
/

ALTER TABLE AG_ACQUISIZIONE_ALLEGATI DROP COLUMN ID_DOC_ALLEGATO
/

ALTER TABLE AG_ACQUISIZIONE_ALLEGATI RENAME COLUMN ID_DOC_ALLEGATO_TMP TO ID_DOC_ALLEGATO
/

-- aggiungo i dati di classificazione e fascicolo
ALTER TABLE AG_ACQUISIZIONE_DETERMINE ADD (CLASSIFICA_CODICE VARCHAR2(255 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DETERMINE ADD (CLASSIFICA_DESCRIZIONE VARCHAR2(255 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DETERMINE ADD (CLASSIFICA_DAL DATE)
/
ALTER TABLE AG_ACQUISIZIONE_DETERMINE ADD (FASCICOLO_NUMERO VARCHAR2(255 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DETERMINE ADD (FASCICOLO_ANNO NUMBER(10))
/
ALTER TABLE AG_ACQUISIZIONE_DETERMINE ADD (FASCICOLO_OGGETTO VARCHAR2(4000 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE ADD (CLASSIFICA_CODICE VARCHAR2(255 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE ADD (CLASSIFICA_DESCRIZIONE VARCHAR2(255 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE ADD (CLASSIFICA_DAL DATE)
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE ADD (FASCICOLO_NUMERO VARCHAR2(255 BYTE))
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE ADD (FASCICOLO_ANNO NUMBER(10))
/
ALTER TABLE AG_ACQUISIZIONE_DELIBERE ADD (FASCICOLO_OGGETTO VARCHAR2(4000 BYTE))
/
ALTER TABLE FIRMATARI ADD ( UTENTE_FIRMATARIO_EFFETTIVO VARCHAR2(255 BYTE) )
/

update firmatari set utente_firmatario_effettivo = utente_firmatario where firmato = 'Y'
/


-- aggiungo il codice della tipologia di allegato
ALTER TABLE AG_ACQUISIZIONE_ALLEGATI ADD (TIPO_ALLEGATO VARCHAR2(255 BYTE))
/

-- metto il tipo di allegato di default:
update tipi_allegato set codice = 'ALLEGATO_GENERICO' where codice is NULL
/

update allegati a set a.codice = (select ta.codice from tipi_allegato ta where ta.id_tipo_allegato = a.id_tipo_allegato) where a.id_tipo_allegato is not null
/

-- #22789 aggiungo il riferimento dei destinatari interni/esterni nella stampa seduta.
ALTER TABLE DESTINATARI_NOTIFICHE ADD (ID_SEDUTA_STAMPA NUMBER(19))
/

ALTER TABLE DESTINATARI_NOTIFICHE ADD CONSTRAINT desnot_sedsta_fk FOREIGN KEY (ID_SEDUTA_STAMPA) REFERENCES ODG_SEDUTE_STAMPE (ID_SEDUTA_STAMPA) ENABLE
/

-- #22789 modifico il metodo di invio PEC con un metodo automatico e non più "CLIENT"
update wkf_diz_azioni set tipo = 'AUTOMATICA' where nome_metodo ='notificaPEC'
/

-- #22789 rinomino la colonna riferimenti_pec in riferimento_pec (siccome conterrà un unico riferimento)
ALTER TABLE odg_sedute_stampe rename column riferimenti_pec to riferimento_pec
/
ALTER TABLE ODG_SEDUTE_STAMPE_STORICO rename column riferimenti_pec to riferimento_pec
/

-- aggiorno l'impostazione della jworklist per consentire SmartDesktop
update impostazioni set valore ='JWorklistService' where valore = 'Y' and codice = 'JWORKLIST'
/

-- aggiorno l'impostazione del wsdl della jworklist:
update impostazioni set valore = substr(valore, 1, length(valore)-5) where valore like '%?wsdl' and codice = 'JWORKLIST_WSDL_URL'
/