--liquibase formatted sql
--changeset rdestasio:install_20200221_ad4_04 runOnChange:true

CREATE OR REPLACE FORCE VIEW AD4_V_PROVINCE
(
   PROVINCIA,
   DENOMINAZIONE,
   DENOMINAZIONE_AL1,
   DENOMINAZIONE_AL2,
   REGIONE,
   SIGLA,
   UTENTE_AGGIORNAMENTO,
   DATA_AGGIORNAMENTO
)
AS
   SELECT PROVINCIA,
          DENOMINAZIONE,
          DENOMINAZIONE_AL1,
          DENOMINAZIONE_AL2,
          REGIONE,
          SIGLA,
          UTENTE_AGGIORNAMENTO,
          DATA_AGGIORNAMENTO
     FROM AD4_PROVINCE
/



