--liquibase formatted sql
--changeset rdestasio:2.5.2.0_20200221_01

CREATE TABLE TIPI_BUDGET
(
   ID_TIPO_BUDGET   NUMBER (19) NOT NULL,
   VERSION          NUMBER (19) NOT NULL,
   TITOLO           VARCHAR2 (255 BYTE),
   ANNO             NUMBER(4) NOT NULL,
   IMPORTO_INIZIALE NUMBER(19,2) NOT NULL,
   IMPORTO_PRENOTATO NUMBER(19,2),
   IMPORTO_AUTORIZZATO NUMBER(19,2),
   IMPORTO_DISPONIBILE NUMBER(19,2),
   
   ENTE             VARCHAR2 (255 BYTE) NOT NULL,
   DATA_INS         DATE NOT NULL,
   DATA_UPD         DATE NOT NULL,
   UTENTE_INS       VARCHAR2 (255 BYTE) NOT NULL,
   UTENTE_UPD       VARCHAR2 (255 BYTE) NOT NULL,
   UNITA_PROGR      NUMBER (19) NOT NULL,
   UNITA_DAL        DATE NOT NULL,
   UNITA_OTTICA     VARCHAR2 (255 BYTE) NOT NULL,
   UTENTE           VARCHAR2 (255 BYTE),
   VALIDO           CHAR (1 BYTE) NOT NULL,
   ATTIVO           CHAR (1 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/

CREATE TABLE TIPI_BUDGET_STORICO
(
   ID_TIPO_BUDGET_STORICO   NUMBER (19) NOT NULL,
   ID_TIPO_BUDGET   NUMBER (19) NOT NULL,
   VERSION          NUMBER (19) NOT NULL,
   TITOLO           VARCHAR2 (255 BYTE),
   ANNO             NUMBER(4) NOT NULL,
   IMPORTO_INIZIALE NUMBER(19,2) NOT NULL,
   IMPORTO_PRENOTATO NUMBER(19,2),
   IMPORTO_AUTORIZZATO NUMBER(19,2),
   IMPORTO_DISPONIBILE NUMBER(19,2),

   ENTE             VARCHAR2 (255 BYTE) NOT NULL,
   DATA_INS         DATE NOT NULL,
   DATA_UPD         DATE NOT NULL,
   UTENTE_INS       VARCHAR2 (255 BYTE) NOT NULL,
   UTENTE_UPD       VARCHAR2 (255 BYTE) NOT NULL,
   UNITA_PROGR      NUMBER (19) NOT NULL,
   UNITA_DAL        DATE NOT NULL,
   UNITA_OTTICA     VARCHAR2 (255 BYTE) NOT NULL,
   UTENTE           VARCHAR2 (255 BYTE),
   VALIDO           CHAR (1 BYTE) NOT NULL,
   ATTIVO           CHAR (1 BYTE) NOT NULL,
   MOTIVAZIONI      VARCHAR2 (4000 BYTE) NOT NULL

)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/

CREATE TABLE BUDGET
(
   ID_BUDGET      NUMBER (19) NOT NULL,
   ID_DETERMINA   NUMBER (19),
   ID_PROPOSTA_DELIBERA NUMBER (19),
   ID_TIPO_BUDGET NUMBER (19) NOT NULL,
   IMPORTO        NUMBER (19, 2) NOT NULL,
   SEQUENZA       NUMBER (19) NOT NULL,
   APPROVATO      CHAR (1 BYTE) NOT NULL,
   VERSION        NUMBER (19) NOT NULL,
   ENTE           VARCHAR2 (255 BYTE) NOT NULL,
   DATA_INS       DATE NOT NULL,
   DATA_UPD       DATE NOT NULL,
   UTENTE_INS     VARCHAR2 (255 BYTE) NOT NULL,
   UTENTE_UPD     VARCHAR2 (255 BYTE) NOT NULL,
   VALIDO         CHAR (1 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/