--liquibase formatted sql
--changeset rdestasio:2.4.6.0_20200221_01

ALTER TABLE ODG_ESITI ADD (ID_REGISTRO_DELIBERA VARCHAR2(255 BYTE))
/

ALTER TABLE ODG_SEDUTE ADD (LINK VARCHAR2(4000 BYTE))
/

ALTER TABLE TIPI_REGISTRO ADD (PAGINA_UNICA CHAR(1 BYTE) DEFAULT 'Y' NOT NULL)
/

UPDATE TIPI_REGISTRO SET PAGINA_UNICA = VISUALIZZATORE
/

ALTER TABLE TIPI_DELIBERA ADD (SEQUENZA NUMBER(19))
/