--liquibase formatted sql
--changeset rdestasio:2.1.2.0_20200221_01

-- gestione del certificato di esecutività per le determine
ALTER TABLE TIPI_DETERMINA ADD (ID_TIPO_CERT_ESEC NUMBER(19))
/

CREATE INDEX TIPDET_TIPCER_ESEC_FK ON TIPI_DETERMINA (ID_TIPO_CERT_ESEC) LOGGING NOPARALLEL
/

ALTER TABLE TIPI_DETERMINA ADD (CONSTRAINT TIPDET_TIPCER_ESEC_FK FOREIGN KEY (ID_TIPO_CERT_ESEC) REFERENCES TIPI_CERTIFICATO (ID_TIPO_CERTIFICATO) ENABLE VALIDATE)
/

-- amplio la colonna campi_protetti siccome nel flusso per pistoia proteggo tutti i campi e sforo la dimensione di 255
ALTER TABLE DETERMINE MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/

ALTER TABLE DELIBERE MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/

ALTER TABLE PROPOSTE_DELIBERA MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/

ALTER TABLE VISTI_PARERI MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/

ALTER TABLE DETERMINE_STORICO MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/

ALTER TABLE PROPOSTE_DELIBERA_STORICO MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/

ALTER TABLE VISTI_PARERI_STORICO MODIFY(CAMPI_PROTETTI VARCHAR2(4000 BYTE))
/