--liquibase formatted sql
--changeset rdestasio:install_20200221_integrazioni_08

-- QUESTA VISTA VIENE USATA DA AGSPR

CREATE OR REPLACE FORCE VIEW GDM_ODG_ESITI
(
   ID_ESITO,
   VERSION,
   ID_COMMISSIONE,
   ID_COMMISSIONE_ARRIVO,
   DATA_INS,
   DESCRIZIONE,
   ENTE,
   ESITO_STANDARD,
   GESTIONE_ESECUTIVITA,
   DATA_UPD,
   NOTIFICA_VERBALIZZAZIONE,
   SEQUENZA,
   TESTO_AUTOMATICO,
   TITOLO,
   UTENTE_INS,
   UTENTE_UPD,
   VALIDO,
   VALIDO_AL,
   VALIDO_DAL,
   PROGRESSIVO_CFG_ITER,
   CREA_DELIBERA,
   DETERMINA,
   PROSSIMA_SEDUTA,
   TITOLO_STANDARD
)
AS
   SELECT e.ID_ESITO ID_ESITO,
          e.VERSION VERSION,
          e.ID_COMMISSIONE ID_COMMISSIONE,
          e.ID_COMMISSIONE_ARRIVO ID_COMMISSIONE_ARRIVO,
          e.DATA_INS DATA_INS,
          e.DESCRIZIONE DESCRIZIONE,
          e.ENTE ENTE,
          e.ESITO_STANDARD ESITO_STANDARD,
          e.GESTIONE_ESECUTIVITA GESTIONE_ESECUTIVITA,
          e.DATA_UPD DATA_UPD,
          e.NOTIFICA_VERBALIZZAZIONE NOTIFICA_VERBALIZZAZIONE,
          e.SEQUENZA SEQUENZA,
          e.TESTO_AUTOMATICO TESTO_AUTOMATICO,
          e.TITOLO TITOLO,
          e.UTENTE_INS UTENTE_INS,
          e.UTENTE_UPD UTENTE_UPD,
          e.VALIDO VALIDO,
          e.VALIDO_AL VALIDO_AL,
          e.VALIDO_DAL VALIDO_DAL,
          e.PROGRESSIVO_CFG_ITER PROGRESSIVO_CFG_ITER,
          es.CREA_DELIBERA CREA_DELIBERA,
          es.DETERMINA DETERMINA,
          es.PROSSIMA_SEDUTA PROSSIMA_SEDUTA,
          es.TITOLO TITOLO_STANDARD
     FROM odg_esiti e, odg_esiti_standard es
    WHERE valido = 'Y' AND e.esito_standard = es.esito_standard
/

