--liquibase formatted sql
--changeset rdestasio:2.5.1.0_20200221_01

ALTER TABLE TIPI_DETERMINA ADD (CUP_VISIBILE CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/

ALTER TABLE TIPI_DETERMINA ADD (CUP_OBBLIGATORIO CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/

