--liquibase formatted sql
--changeset rdestasio:2.2.0.0_20200221_01

-- aggiunto campo stampa unica per le proposte di delibera
ALTER TABLE PROPOSTE_DELIBERA ADD (ID_FILE_ALLEGATO_STAMPA_UNICA  NUMBER(19))
/

CREATE INDEX PROP_FILALL_SU_FK ON PROPOSTE_DELIBERA
(ID_FILE_ALLEGATO_STAMPA_UNICA)
LOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

ALTER TABLE PROPOSTE_DELIBERA ADD (
  CONSTRAINT PROP_FILALL_SU_FK
  FOREIGN KEY (ID_FILE_ALLEGATO_STAMPA_UNICA)
  REFERENCES FILE_ALLEGATI (ID_FILE_ALLEGATO)
  ENABLE VALIDATE)
/

ALTER TABLE PROPOSTE_DELIBERA_STORICO ADD (ID_FILE_ALLEGATO_STAMPA_UNICA  NUMBER(19))
/

CREATE INDEX PROPSTO_FILALL_SU_FK ON PROPOSTE_DELIBERA_STORICO
(ID_FILE_ALLEGATO_STAMPA_UNICA)
LOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

ALTER TABLE PROPOSTE_DELIBERA_STORICO ADD (
  CONSTRAINT PROPSTO_FILALL_SU_FK
  FOREIGN KEY (ID_FILE_ALLEGATO_STAMPA_UNICA)
  REFERENCES FILE_ALLEGATI_STORICO (ID_FILE_ALLEGATO_STORICO)
  ENABLE VALIDATE)
/

ALTER TABLE PROPOSTE_DELIBERA ADD (PARERE_REVISORI_CONTI CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/

ALTER TABLE PROPOSTE_DELIBERA_STORICO ADD (PARERE_REVISORI_CONTI CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/

ALTER TABLE DETERMINE ADD (INVIATO_TESORIERE     CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
                           NUMERO_PROT_TESORIERE NUMBER(10),
                           DATA_PROT_TESORIERE   DATE,
                           NOTE_TESORIERE        VARCHAR2(4000 BYTE))
/

ALTER TABLE TIPI_ALLEGATO ADD (ID_MODELLO_TESTO  NUMBER(19),
                               CODICE            VARCHAR2(255 BYTE),
                               MODIFICABILE      CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
                               MODIFICA_CAMPI    CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
                               TIPOLOGIA         VARCHAR2(255 BYTE),
                               STATO_FIRMA       VARCHAR2(255 BYTE),
                               STAMPA_UNICA      CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/

UPDATE TIPI_ALLEGATO SET TIPOLOGIA = 'Delibera' WHERE DELIBERA = 'Y'
/

UPDATE TIPI_ALLEGATO T SET STATO_FIRMA = (SELECT VALORE FROM IMPOSTAZIONI WHERE CODICE = 'ALLEGATO_STATO_FIRMA_DEFAULT' and ENTE = T.ENTE) WHERE STATO_FIRMA IS NULL
/

UPDATE TIPI_ALLEGATO SET TIPOLOGIA = 'PARERE', CODICE = 'SCHEDA_CONTABILE' WHERE CODICE = 'Scheda Contabile Delibera'
/

UPDATE TIPI_ALLEGATO SET TIPOLOGIA = 'VISTO', CODICE = 'SCHEDA_CONTABILE' WHERE CODICE = 'Scheda Contabile Determina'
/

UPDATE TIPI_ALLEGATO SET TIPOLOGIA = 'PROPOSTA_DELIBERA', CODICE = 'ALLEGATO_MODIFICABILE' WHERE CODICE = 'Allegato Modificabile'
/

ALTER TABLE TIPI_ALLEGATO DROP COLUMN DELIBERA
/

-- campi aggiunti per integrazione contabile con DataManagemente - Comune di Modena
ALTER TABLE MOVIMENTI_CONTABILI ADD (STATO VARCHAR2(255 BYTE) DEFAULT 'DA_NON_INVIARE' NOT NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (STATO_DESCRIZIONE VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (TIPO_CODICE_STATISTICO_1 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (TIPO_CODICE_STATISTICO_2 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (TIPO_CODICE_STATISTICO_3 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (TIPO_CODICE_STATISTICO_4 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (TIPO_CODICE_STATISTICO_5 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_STATISTICO_1 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_STATISTICO_2 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_STATISTICO_3 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_STATISTICO_4 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_STATISTICO_5 VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_ID_EUROPEO VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_VOCE_MINISTERIALE VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_SIOPE VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (TIPO_USCITA VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CIG VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (CUP VARCHAR2(255 BYTE) NULL)
/

ALTER TABLE MOVIMENTI_CONTABILI ADD (DATA_SCADENZA DATE NULL)
/

-- campi aggiunti per gestire i valori multipli in mapping-integrazioni
ALTER TABLE MAPPING_INTEGRAZIONI ADD (SEQUENZA NUMBER(19) DEFAULT 0 NOT NULL)
/

ALTER TABLE MAPPING_INTEGRAZIONI ADD (DESCRIZIONE VARCHAR(255) NULL)
/

-- indici per integrazione con cfa
begin execute immediate 'create index dete_cf_prop_ik on determine(anno_proposta,numero_proposta)'; exception when others then null; end;
/

ALTER TABLE TIPI_VISTO_PARERE ADD (PUBBLICA_ALLEGATI CHAR(1 BYTE) DEFAULT 'N' NOT NULL)
/

ALTER TABLE VISTI_PARERI_STORICO ADD ( ID_DELIBERA NUMBER(19))
/

CREATE INDEX VISPAR_STO_DEL_FK ON VISTI_PARERI_STORICO (ID_DELIBERA) LOGGING NOPARALLEL
/

update visti_pareri_storico storico
   set storico.id_delibera =
          (select visto.id_delibera
             from visti_pareri visto
            where visto.id_visto_parere = storico.id_visto_parere)
 where storico.id_determina is null and storico.id_proposta_delibera is null and storico.id_delibera is null
/

update mapping_integrazioni mi
   set mi.valore_esterno = (select c.tipo_oggetto || ',' || mi.valore_esterno from categorie c where mi.valore_interno = c.codice)
 where mi.categoria = 'CASA_DI_VETRO' AND mi.codice = 'CATEGORIA'
/

update impostazioni set valore = 'UTENTE', predefinito = 'UTENTE' where codice = 'JWORKLIST_ELIMINA_NOTIFICA_UO'
/

-- gestione dei file "originali prima della firma" e "odt" su GDM
ALTER TABLE FILE_ALLEGATI ADD (ID_FILE_ALLEGATO_ORIGINALE NUMBER(19))
/

ALTER TABLE FILE_ALLEGATI ADD CONSTRAINT FIALORIG_FIAL_FK FOREIGN KEY (ID_FILE_ALLEGATO_ORIGINALE) REFERENCES FILE_ALLEGATI (ID_FILE_ALLEGATO) ENABLE VALIDATE
/
