--liquibase formatted sql
--changeset rdestasio:2.3.2.0_20200221_01

ALTER TABLE DETERMINE ADD (DATA_ORDINAMENTO DATE)
/

ALTER TABLE PROPOSTE_DELIBERA ADD (DATA_ORDINAMENTO DATE)
/

ALTER TABLE VISTI_PARERI ADD (DATA_ORDINAMENTO DATE)
/